services:
  woof-api-db:
    container_name: woof-api-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: walkwoof
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3366:3306"
    volumes:
      - woof-api-db-data:/var/lib/mysql
    networks:
      - woof-network

  woof-api:
    container_name: woof-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - woof-api-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://woof-api-db:3306/walkwoof
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    networks:
      - woof-network

volumes:
  woof-api-db-data:

networks:
  woof-network:
    driver: bridge